### ISSUE TITLE
make*.formatFilePath overwriting issue

### ISSUE THREAD

**Issue by NamesMT** [vHeemstra/vite-plugin-imagemin#2]
With the formatFilePath of makeWebP set to `(file) => file` (same as root plugins), the actual final built file is inconsistent, sometimes the said "skipped" larger webp file replaces the optimized, and the sometimes the smaller webp file not there/replaced by optimized.
Tested with both skipIfLargerThan: 'smallest' | 'optimized'

**Comment by vHeemstra** [comment]
If you use the same filename for the optimized and the webp versions, it will of course overwrite. The reason this might be inconsistent is that, for speed optimization reasons, all files are processed async. So, you are left with a classic race condition.

As a side note, the WebP images should have the `.webp` file extension, which can't happen with `(file) => file`.

**Comment by NamesMT** [comment]
Yes I know I'm doing a hackish way with webp doing the same extension cause it's a local project where I can control all browsers accessed would supports it.
Could be nice there is a way to delay the make* to be built only after the optimized, still processed async and stored temporarily somewhere then moved to dest if confirmed not skipped.

**Comment by NamesMT** [comment]
Hacks isn't a good practice.
