### ISSUE TITLE
Caching does not work properly

### ISSUE THREAD

**Issue by naranjamecanica** [vHeemstra/vite-plugin-imagemin#7]
Hi, just to let you know, i've found out that the caching is not working properly yet... 😱

- When building for a second time, the uncompressed variant is copied instead of keeping the optimised
- When using emptyOutDir in Vite we should use a cached version of the compressed image.

I'm going to look into it, but that will be probably beginning of next week.

A new release with cache:false as default could be a good idea...

**Comment by vHeemstra** [comment]
Yes, the problem is that (by default) Vite empties the `outDir`, so the optimized files are deleted on every build.

So although the cache recognizes that the input file has not changed between builds, it will still force re-process because the output files are no longer there (`outputsStillExist` check).

**Comment by vHeemstra** [comment]
So I made a solution.

All output files are now also stored in a cache folder (`node_modules/.vite-plugin-imagemin`.
When processing all files, it:
1) Checks if the input file has changed
2) If unchanged, check each output file
3) (Per output file) Check if it exists in the cache folder and if that file has changed
4) If present and unchanged, use this cached version by copying it to the `outDir`
5) All other situations: re-process the input file

- This works for assets as well as static files in `publicDir`.
- This works with both `emptyOutDir` on `true` and `false`.
- Only downside: a duplicate folder with all assets after processing inside `node_modules`. And currently there is no cleanup of this folder, only adding new files and overwriting updated ones. 

@naranjamecanica 
Hope this works for you as well!
Do you have any ideas on how to implement a good cleanup routine for the cache folder?

**Comment by naranjamecanica** [comment]
Hej, cool addition! Only in my setup the caching dir gets created in my dist folder, see screenshot... 😅
<img width="826" alt="image" src="https://github.com/vHeemstra/vite-plugin-imagemin/assets/884899/5f118b76-29d7-47e3-bacd-f2099f3dbdf3">

I'm working on a tight deadline right now, so can look in to it next week.. maybe using the same directory as the caching dictionary is also a good idea. 👍🏻

**Comment by vHeemstra** [comment]
The folder used for caching the output files is relative to the root folder as configured for Vite (so `<root>/node_modules/.vite-plugin-imagemin/`).

See also [`root` configuration](https://vitejs.dev/config/shared-options#root) in the Vite documentation.

**Comment by vHeemstra** [comment]
Also, by default the dust folder would be a subfolder inside the root folder. From the screenshot I gather you're using the root folder as the dist/outDir folder as well.

Either way, since `package.json` is in the root folder, the `node_modules` folder would be there too by convention, right?

**Comment by vHeemstra** [comment]
Note:
There was a different error in the cache checks (handling of async/await), which has been fixed in version 1.1.2.

**Comment by naranjamecanica** [comment]
Yes, i specify an other root dir for my projects

```
const options: UserConfig = {
    root: path.resolve(cwd, 'source'),
	...
}
```

The root dir is not connected to the root of the whole project where `node_modules` resides but to the directory where the entry points of the projects are located. The caching module uses an different approach, I'll make a pull request to mimic that behaviour.

About a cleanup routine for the cache, that can be a tricky one, but i'll give it a shot later.

**Comment by vHeemstra** [comment]
See #10
